config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  resources :wikis do
    resources :collaborations
  end



  resources :users

  resources :charges, only: [:new, :create]

  root 'welcome#index'
end

app/models/wiki.rb
include ApplicationHelper

class Wiki < ActiveRecord::Base

  has_many :collaborations, dependent: :destroy
  has_many :users, through: :collaborations


  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true

  def private?
   self.private == true
  end


  def find_users
    User.all.map do |x|
      x.email
    end
  end

  def add_collaborator(collab_id)
    Collaboration.create(user_id: collab_id, wiki_id: self.id)
  end

  def remove_collaborator(collab_id)
    Collaboration.delete(user_id: collab_id, wiki_id: self.id)
  end

  def markdown_title
    markdown_to_html (self.title)
  end

  def markdown_body
    markdown_to_html (self.body)
  end

  private

  def make_public
    self.private = false
  end



end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  # before_action :require_sign_in, except: :show
  # before_action :authorize_user, except: [:show, :new, :create]

  def show
    @wiki = Wiki.find(params[:id])
  end

  def index
    @wiki = Wiki.all
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.create!(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki has been saved"
      redirect_to wikis_path
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was updated"
      redirect_to wiki_index_path
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "Wiki was deleted successfully"
    else
      flash[:alert] = "There was an error deleting the wiki"
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end


end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authorize_user, only: [:destroy]
  before_action :authorize_edit, only: [:edit, :update]


  def show
    @wiki = Wiki.find(params[:id])
  end

  def index
    @public_wikis = Wiki.where(private: false)
    @wiki = Wiki.all
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.create(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki has been saved"
      redirect_to wikis_path
    else
      flash[:error] = "Error. Could not save the wiki."
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end


  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was updated"
      redirect_to wikis_path
    end
    if params[:wiki][:collaborations]
      collaborator = User.find_by(email: params[:wiki][:collaborations])
      @wiki.add_collaborator(collaborator.id)
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "Wiki was deleted successfully"
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting the wiki"
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user_id)
  end

  def add_collaborator(collaborator)
    self.collaboration << collaborator
  end


  def authorize_edit
    unless current_user.admin? || current_user.premium?
      flash[:alert] = "Upgrade your account to access this feature!"
      redirect_to wiki_path
    end
  end

  def authorize_user
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do this!"
      redirect_to wiki_path
    end
  end

end

app/helpers/wiki_helper.rb
module WikiHelper
  def user_is_able_to_edit
    current_user || current_user.admin?
  end
  def add_collaborator(collab_id)
    collaborator = User.find_by(email: collab_id)
    @wiki.add_collaborator(collab_id)
  end
end

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Don't use curse words</li>
      <li>Include accurate information only.</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: "Enter wiki title" %><br><br>

      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %><br><br>


      <%= f.check_box :private %> Private Wiki<br><br><br>

      <%= f.submit "Update", class: 'btn btn-success', method: :update %>
    <% end %>
  </div>
  <%= render partial: 'collaborations/form', locals: { wiki: @wiki } %>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<h3><%= link_to 'Create A Wiki', new_wiki_path, class: 'btn btn-success'%></h3><br>

<% @wiki.each do |w| %>
  <% unless (w.private == true && current_user.role == 'standard') %>
    <%= link_to w.markdown_title, w %>
    <small>
      Submitted <%= time_ago_in_words(w.created_at) %>
      <br><br>
    </small>
  <% end %>
<% end %>


<%= link_to 'Home', '/', class: 'btn btn-primary' %><br><br>

app/views/wikis/new.html.erb
<h1> New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Don't use curse words</li>
      <li>Include accurate information only.</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div><br>

  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %><br><br>

      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %><br><br>

      <% if current_user.role == "premium" || current_user.role == "admin" %>
        <%= f.check_box :private %> Private Topic<br><br>
      <% end %>

      <%= f.submit "Create", class: 'btn btn-success', method: :create %>
      <%= link_to "Cancel", wikis_path, class: 'btn btn-danger' %>

    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.markdown_title %></h1>
<h4>Created by: <%= @wiki.user.email rescue "Unknown" %></h4><br>
<%= link_to "Back", wikis_path, class: 'btn btn-primary' %> -
<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-primary' %> -
<%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %><br><br>
<h5>Private Wiki:
                <% if @wiki.private %>
                  <input type="checkbox" checked="checked">
                <% else %>
                  <input type="checkbox">
                <% end %>
</h5>

<h5>Collaborators:</h5>
                  <div style="margin-left:30px;">
                    <% @wiki.collaborations.each do |c| %>
                      <div class="row">
                        <%= c.user.email %>
                      </div>
                    <% end %>
                  </div>



<br>
<div style="font-family: Verdana, Geneva, sans-serif;margin:15px;">
  <%= @wiki.markdown_body %>
</div>
<br><br>