config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  resources :wikis do
    resources :collaborations
  end



  resources :users

  resources :charges, only: [:new, :create]

  root 'welcome#index'
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user #fix relationship

# method to update Collaborators
  def update_collaborations(collaborators)
    
  end

  def collaboration_user
    collaborations.collect(:user_id)
  end

end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_wiki

  def new
    @collaboration = Collaboration.new
  end

  def show
    @collaboration = Collaboration.find(params[:user_id])
  end

  def edit
    @collaboration = Collaboration.find(params[:user_id])
  end

  def update
    @collaboration.update_attributes(collaboration_params)
    if @wiki.save
      flash[:notice] = "Wiki was updated"
      redirect_to wikis_path
    end
  end

  def create
    user = User.find_by(email: params["collaboration"]["user"])
    @collaboration = Collaboration.create!(wiki_id: params["wiki_id"], user_id: user.id)

     if @collaboration.save
       flash[:notice] = "Collaboration was saved."
       redirect_to wiki_path(@wiki)
     else
       flash[:error] = "Error. Could not save the collaboration."
       redirect_to wiki_path(@wiki)
     end
  end

  def destroy
     @collaboration = Collaboration.find(params["id"])
    if @collaboration.destroy
       flash[:notice] = "#{@collaboration.user.email} was successfully removed."
       redirect_to wiki_path(@wiki)
     else
       flash[:error] = "Error. Could not remove the collaboration."
       redirect_to wiki_path(@wiki)
     end
  end

  private
  
  def set_wiki
    @wiki = Wiki.find(params["wiki_id"])
  end


  def collaboration_params
    params.require(:collaboration).permit(:wiki_id, :user_id, :collaboration)
  end


end

app/views/collaborations/_form.html.erb
<h4>Current Collaborator(s): </h4>
<div style="margin-left:30px;">
  <% wiki.collaborations.each do |c| %>
    <div class="row">
      <%= link_to 'X', wiki_collaboration_path(wiki.id, c), method: :delete, class: "btn btn-danger btn-xs"%> <%= c.user.email %>
    </div>
  <% end %>
</div><br><br>

<%= form_for [wiki, Collaboration.new] do |c| %>
  <%= c.select :user, wiki.find_users, :include_blank => true, class: 'form-control' %><br><br>

  <%= c.submit "Add Collaborator", class: 'btn btn-primary' %>
  <br><br><br>
<% end %>