config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  resources :wikis do
    resources :collaborations
  end



  resources :users

  resources :charges, only: [:new, :create]

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>

    Signed in as: <strong><%= current_user.email %> (<%= current_user.current_sign_in_ip %>)</strong> |
    <% if current_user.role == 'standard' %>
      <%= link_to "Upgrade to Premium", new_charge_path, class: 'navbar-link' %> -
    <% elsif current_user.role == 'premium' %>
      Account Status: <span style="color:gold;font-weight:bold;text-decoration:underline">Premium</span> -
    <% else %>
      Account Status: <span style="color:red;font-weight:bold;text-decoration:underline">Admin</span> -
    <% end %>
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %><br><br>
    <%= link_to 'Home', '/', class: 'btn btn-primary' %>  -
    <%= link_to 'Wikis', wikis_path, class: 'btn btn-primary' %><br>

  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  <% end %><br>


   <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
   <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
   <% end %>

<%= yield %>


</body>
</html>